const fs = require('node:fs');
const {test, expect} = require('@playwright/test');
const Ajv = require('ajv');
const addFormats = require('ajv-formats');
const spec = JSON.parse(fs.readFileSync('dist/runtime-openapi.json'));
const ajv = new Ajv({strict:false,allErrors:true});addFormats(ajv);
const tenant = process.env.JUDEOS_BROWSER_TENANT || '00000000-0000-4000-8000-000000000101';
const ownerLogin=process.env.JUDEOS_BROWSER_OWNER || 'synthetic.browser.owner';
const coachLogin=process.env.JUDEOS_BROWSER_COACH || 'synthetic.browser.coach';
const staffPath = `/api/v1/tenants/${tenant}/staff`;
const password = 'synthetic-browser-password-123';
test('real HTTPS UI: invite → password → login → roles → revoke → logout',async({page,context,browser,baseURL})=>{
  const file = process.env.JUDEOS_BOOTSTRAP_LINK_FILE;
  test.skip(!file,'requires a disposable synthetic owner invitation file');
  const {token} = JSON.parse(fs.readFileSync(file,'utf8'));
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const validation=[];
  page.on('response',response=>{
    const pathname=new URL(response.url()).pathname;
    if (!pathname.startsWith('/api/v1/')) return;
    validation.push((async()=>{
      const route=pathname.replace(tenant,'{tenant_id}').replace(/\/staff\/[a-f0-9-]{36}/,'/staff/{membership_id}');
      const op=spec.paths[route]?.[response.request().method().toLowerCase()];
      if (!op) throw new Error('Undocumented runtime response');
      let definition=op.responses[String(response.status())];
      if (!definition) throw new Error(`Undocumented status ${response.status()}`);
      if (definition.$ref) definition=definition.$ref.slice(2).split('/').reduce((v,k)=>v[k],spec);
      expect(response.headers()['cache-control']).toBe('no-store');
      if (response.status()!==204) {
        const validate=ajv.compile({...definition.content['application/json'].schema,components:spec.components});
        expect(validate(await response.json()),JSON.stringify(validate.errors)).toBe(true);
      }
    })());
  });
  await page.goto(`/#token=${token}`);
  await expect(page.getByRole('heading',{name:'Установить пароль'})).toBeVisible();
  expect(new URL(page.url()).hash).toBe('');
  await page.getByLabel('Новый пароль').fill(password);
  await page.getByRole('button',{name:'Установить пароль',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Пароль установлен');
  await page.getByLabel('Логин',{exact:true}).fill(ownerLogin);
  await page.getByLabel('Пароль',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Сотрудники',exact:true})).toBeVisible();
  for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:850});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
  const cookies=await context.cookies();const session=cookies.find(c=>c.name==='__Host-judeos-session');
  expect(session.secure).toBe(true);expect(session.httpOnly).toBe(true);expect(session.sameSite).toBe('Lax');
  expect(await page.evaluate(()=>[localStorage.length,sessionStorage.length])).toEqual([0,0]);
  expect(await page.evaluate(()=>document.cookie)).not.toContain('__Host-judeos-session');
  const ownerRow=page.locator('.staff li').filter({has:page.getByText(ownerLogin,{exact:true})});
  page.once('dialog',d=>d.accept());await ownerRow.getByRole('button',{name:'Отозвать доступ',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Изменение отклонено');
  await page.getByLabel('Логин нового сотрудника').fill(coachLogin);
  await page.getByRole('button',{name:'Создать приглашение',exact:true}).click();
  const link=await page.getByLabel('Одноразовая ссылка').inputValue();
  await page.getByRole('button',{name:'Скрыть ссылку',exact:true}).click();
  const coachContext=await browser.newContext({baseURL,ignoreHTTPSErrors:false});
  const coach=await coachContext.newPage();await coach.goto(link);
  await coach.getByLabel('Новый пароль').fill(password);await coach.getByRole('button',{name:'Установить пароль',exact:true}).click();
  await expect(coach.getByRole('status')).toContainText('Пароль установлен');
  await coach.getByLabel('Логин',{exact:true}).fill(coachLogin);await coach.getByLabel('Пароль',{exact:true}).fill(password);await coach.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(coach.getByRole('heading',{name:'Рабочее пространство'})).toBeVisible();
  await expect(coach.getByRole('heading',{name:'Сотрудники',exact:true})).toHaveCount(0);
  expect(await coach.evaluate(async path=>(await fetch(path)).status,staffPath)).toBe(403);
  await page.reload();await expect(page.getByRole('heading',{name:'Сотрудники',exact:true})).toBeVisible();
  const coachRow=page.locator('.staff li').filter({has:page.getByText(coachLogin,{exact:true})});
  await coachRow.getByLabel('Менеджер',{exact:true}).check();await coachRow.getByRole('button',{name:'Сохранить роли',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Доступ обновлён');
  expect(await coach.evaluate(async()=> (await fetch('/api/v1/access/session')).status)).toBe(401);
  await coach.reload();await expect(coach.getByRole('heading',{name:'Вход в клуб'})).toBeVisible();
  await coach.getByLabel('Логин',{exact:true}).fill(coachLogin);await coach.getByLabel('Пароль',{exact:true}).fill(password);await coach.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(coach.getByText('Ваши роли: Тренер, Менеджер.')).toBeVisible();
  page.once('dialog',d=>d.accept());await coachRow.getByRole('button',{name:'Отозвать доступ',exact:true}).click();await expect(page.getByRole('status')).toContainText('Доступ обновлён');
  expect(await coach.evaluate(async()=> (await fetch('/api/v1/access/session')).status)).toBe(401);
  await coachContext.close();
  await page.screenshot({path:'dist/access-staff.png',fullPage:true});
  await page.getByRole('button',{name:'Выйти',exact:true}).click();await expect(page.getByRole('heading',{name:'Вход в клуб'})).toBeVisible();
  await Promise.all(validation);expect(errors).toEqual([]);
});
