/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants/{tenant_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить назначенные занятия за дату
         * @description Принятый #16: текущий назначенный coach. Роли #26 подтверждены: administrator видит занятия клуба своей сети, manager — назначенного ему клуба за дату; coach — только текущие назначения; название operationId сохраняется ради совместимости. planned/in_progress/closed/cancelled, локальная date Europe/Minsk, сортировка starts_at/session_id, cursor связан с actor/tenant/date; каждая страница проверяет актуальные grants. Бывшее назначение само по себе не даёт историю. Wire-расширение ожидает приёмки; представление сетевого разрешения согласуется с #21.
         */
        get: operations["listAssignedSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Прочитать занятие и сохранённый состав
         * @description Принятый #16: минимальный журнал текущего назначенного coach. Область #26 подтверждена: administrator читает журнал клуба своей сети, manager — назначенного ему клуба; coach только при текущем назначении. DTO добавляет optional primary_contact (имя и телефон выбранного сейчас проверенного представителя), admission без диагноза и excluded. Старое минимальное DTO #16 сохраняется как совместимый формат. null контакт при отсутствии/истечении/отзыве; fallback запрещён. Семьи, другие представители, основание проверки, финансы, дата рождения не выдаются. Архивный/исключённый участник сохраняет допустимые факты, но контакт/admission не выдаются. История не создаёт бессрочного доступа. Область ролей подтверждена; wire и новые поля приняты в #102, сетевая область принята #27; #29 не выдаёт optional contact/admission.
         */
        get: operations["getSessionJournal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/sessions/{session_id}/attendance/{athlete_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Сохранить одну отметку с проверкой версии
         * @description Принятый #16: активный coach, назначенный сейчас, и Athlete в SessionRoster этого tenant. Проверяются session state и неархивный Athlete в одной транзакции с эффектом/историей/OperationResult. cancelled — 409; planned/in_progress разрешены, closed — исправление текущим назначенным тренером.  base_version относится только к этой отметке; перенос/смена состава не вычисляются из клиентской версии. Автор/время берутся сервером. Новый принятый operation_id повышает версию на 1 даже при том же status и оставляет историю до/после. Та же команда сериализуется по (tenant, actor, operation_id) и возвращает прежний успешный/конфликтный результат после актуальной проверки scope/состояния; другой payload/target — 409 OPERATION_ID_REUSED. Type, /api/v1, target, base_version, status и нормализованная reason входят в hash. 401/403/404, невалидный ввод и отказ по актуальному состоянию не сохраняются как эффект. Конфликт версии сохраняется как терминальный результат ID; после явного решения нужен новый ID/base_version. Повтор не порождает новый аудит/уведомление. Ответ replay описывает исходный результат, не сегодняшнюю версию; перечитать журнал. Нет last-write-wins, финансовых эффектов или Telegram. Срок удаления результатов/ID и recovery — #18/#52; до их согласования синтетический сервис не удаляет результаты. Права #26: administrator клуба своей сети / manager назначенного клуба также ставит/исправляет существующие отметки, включая closed; coach — текущий назначенный. Исключённая строка — 404, cancelled/архив по прежним кодам. Снятие coach не снимает отдельную административную роль. Wire-расширение требует приёмки и не является действующим API; сетевое разрешение согласуется с #21.
         */
        put: operations["setAttendance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/athletes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Поиск и страницы спортсменов
         * @description Минимальная проекция без телефонов, оснований представителей и полного профиля. UUID keyset ORDER BY id, limit 1–100 (default 30), next_cursor null — конец. Поиск q — буквальная подстрока имени без wildcard; не объединяет совпадения. Семьи не имеют archive-флага; state=archived для них отклоняется. Только administrator/manager разрешённого клуба, явный владелец своей сети или отдельный платформенный administrator. FORCE RLS и составные FK сохраняются. Команда атомарна с metadata-only аудитом. operation_id по tenant/actor; canonical v1/type/target/payload/version. Неизвестный сетевой результат повторять с тем же ID/payload, после конфликта — новая команда. Права и актуальность результата перепроверяются перед replay; терминальный конфликт версии сохраняется. Семья/телефон/поступление прав не дают.
         */
        get: operations["listAthletes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/sessions/{session_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Закрыть занятие без заполнения отсутствий
         * @description Принятый wire #26 / PR #102: роли закрытия подтверждены владельцем. Active administrator в клубе своей сети, manager в назначенном ему клубе или текущий назначенный coach этого занятия. Назначение тренером для administrator/manager не требуется. Источник ролей: https://github.com/StarMadeGalaxy/JudeOS/issues/26#issuecomment-6066079471. planned/in_progress → closed; base_version — Session. cancelled запрещено. unmarked сохраняется, результат предупреждает о количестве. При уже closed новый ID не создаёт новый переход (409 SESSION_CLOSED), точный разрешённый replay возвращает старый результат. Переоткрытия нет. Источник: https://github.com/StarMadeGalaxy/JudeOS/issues/26#issuecomment-6060282984. Нет реализации. Правила/атомарность/повтор — api/S1-CONTRACT.md.
         */
        post: operations["closeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/sessions/{session_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Добавить известного участника
         * @description Принятый wire #26 / PR #102; бизнес-минимум/область ролей подтверждены: Active administrator клуба своей сети / manager назначенного клуба или текущий назначенный coach. Только planned/in_progress и неархивный Athlete. base_version — Session. Временное добавление меняет только указанное занятие, без Enrollment/постоянного состава/шаблона/будущих занятий. Постоянную группу составляет manager; trial отдельный флаг, participation=visit для разового визита. Уже активный roster не дублируется; новый ID без эффекта не повышает версию. Исключённая строка без отдельного правила повторного включения даёт 409 ROSTER_EXCLUDED. Отметка не записывается этой командой. Источник: https://github.com/StarMadeGalaxy/JudeOS/issues/26#issuecomment-6060282984. Реализовано #29; optional contact/admission не выдаются. Правила/атомарность/повтор — api/S1-CONTRACT.md.
         */
        post: operations["addKnownRosterAthlete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/sessions/{session_id}/guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создать онлайн-гостя и добавить в занятие
         * @description Принятый wire #26 / PR #102; бизнес-минимум/область ролей подтверждены: Те же права временного add только в указанное занятие; planned/in_progress. Без постоянного зачисления/шаблона/будущего состава. Атомарно Person + Athlete(guest) + SessionRoster без Account/семьи/обязательного контакта. base_version — Session. Телефон необязателен; похожее имя не означает дубль. Стабильные ID сохраняются при переходе в regular; нет offline временных профилей. Источник: https://github.com/StarMadeGalaxy/JudeOS/issues/26#issuecomment-6060282984. Нет реализации. Правила/атомарность/повтор — api/S1-CONTRACT.md.
         */
        post: operations["createSessionGuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/sessions/{session_id}/roster/{athlete_id}/exclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Исключить из активного состава с сохранением истории
         * @description Принятый wire #26 / PR #102; бизнес-минимум/область ролей подтверждены: Только administrator клуба своей сети / manager назначенного клуба; только planned/in_progress. base_version — Session. Сохранённая строка становится excluded=true, остаются отметка/автор/история, физического DELETE нет. Уже excluded новый ID даёт результат без нового эффекта. В closed/cancelled изменение состава запрещено. Coach-only не исключает/не заменяет состав. Исключённая строка доступна разрешённой истории, но не новому контакту/отметке. Источник: https://github.com/StarMadeGalaxy/JudeOS/issues/26#issuecomment-6060282984. Реализовано #29; optional contact/admission не выдаются. Правила/атомарность/повтор — api/S1-CONTRACT.md.
         */
        post: operations["excludeRosterAthlete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionPage: {
            items: components["schemas"]["TrainingSession"][];
            /** @description Непрозрачный cursor; null означает конец. Не snapshot при конкурентном переносе. */
            next_cursor: string | null;
        };
        TrainingSession: {
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            tenant_id: string;
            group: components["schemas"]["NamedId"];
            venue: components["schemas"]["NamedId"];
            /**
             * Format: date-time
             * @description UTC, RFC 3339 с Z; дата списка вычисляется в зоне клуба.
             */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            state: components["schemas"]["SessionState"];
            /** @description Версия состояния, времени, состава и назначений; не версия отметок. */
            version: number;
        };
        NamedId: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** @enum {string} */
        SessionState: "planned" | "in_progress" | "closed" | "cancelled";
        Error: {
            /** @enum {string} */
            code: "INVALID_REQUEST" | "UNAUTHENTICATED" | "LOGIN_FAILED" | "CSRF_REJECTED" | "FORBIDDEN" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "UNSUPPORTED_MEDIA_TYPE" | "PAYLOAD_TOO_LARGE" | "OPERATION_ID_REUSED" | "SESSION_CANCELLED" | "ATHLETE_ARCHIVED" | "RATE_LIMITED" | "INTERNAL_ERROR" | "SERVICE_UNAVAILABLE" | "SESSION_EXPIRED" | "ACCESS_DENIED" | "ACCESS_CONFLICT" | "LINK_INVALID";
            message: string;
            request_id: string;
        };
        SessionJournal: {
            session: components["schemas"]["TrainingSession"];
            roster: components["schemas"]["RosterEntry"][];
        };
        RosterEntry: {
            /** Format: uuid */
            athlete_id: string;
            /** Format: uuid */
            person_id: string;
            display_name: string;
            /** @enum {string} */
            participation: "regular" | "guest" | "visit";
            trial: boolean;
            attendance: components["schemas"]["Attendance"];
            primary_contact?: components["schemas"]["PrimaryContact"];
            admission?: components["schemas"]["AdmissionSummary"];
            /** @description Принятый контракт #26: сохранённая исключённая строка; история/отметка остаются, новые отметки/контакт недоступны. */
            excluded?: boolean;
        };
        Attendance: components["schemas"]["UnrecordedAttendance"] | components["schemas"]["RecordedAttendance"];
        UnrecordedAttendance: {
            /** Format: uuid */
            athlete_id: string;
            /** @enum {string} */
            status: "unmarked";
            version: number;
            /**
             * Format: date-time
             * @enum {string|null}
             */
            recorded_at: null;
            /**
             * Format: uuid
             * @enum {string|null}
             */
            recorded_by_account_id: null;
        };
        RecordedAttendance: {
            /** Format: uuid */
            athlete_id: string;
            status: components["schemas"]["AttendanceStatus"];
            version: number;
            /** Format: date-time */
            recorded_at: string;
            /** Format: uuid */
            recorded_by_account_id: string;
        };
        /**
         * @description Был / Не был / Болел / Не отмечен. trial принадлежит roster.
         * @enum {string}
         */
        AttendanceStatus: "present" | "absent" | "sick" | "unmarked";
        /** @description Принятый контракт #26: только имя выбранного представителя и разрешённый телефон. null — выбор отсутствует/связь отозвана/истекла; без fallback. ID/основание/другие представители не выдаются coach. */
        PrimaryContact: {
            display_name: string;
            /** @description Необязательный номер; null — доступного номера нет. Номер не доказывает связь или права. */
            phone: string | null;
        } | null;
        /** @description Операционный допуск без диагноза/файла; null — сведений нет. Не блокирует запись фактического присутствия. Правила истечения/изменения — #33. */
        AdmissionSummary: {
            /** @enum {string} */
            state: "admitted" | "not_admitted" | "review_required";
            /** Format: date */
            valid_until: string | null;
        } | null;
        AttendanceSaved: {
            /** Format: uuid */
            operation_id: string;
            attendance: components["schemas"]["Attendance"];
        };
        AttendanceCommandConflict: components["schemas"]["Error"] | components["schemas"]["AttendanceConflict"];
        AttendanceConflict: {
            /** @enum {string} */
            code: "ATTENDANCE_VERSION_CONFLICT";
            message: string;
            request_id: string;
            /** Format: uuid */
            operation_id: string;
            current: components["schemas"]["Attendance"];
        };
        SetAttendanceRequest: {
            /**
             * Format: uuid
             * @description Новый UUID для нового намерения; тот же ID и payload при сетевом повторе.
             */
            operation_id: string;
            base_version: number;
            status: components["schemas"]["AttendanceStatus"];
            /** @description Необязательная причина; отсутствие и пустая строка нормализуются одинаково; null запрещён. */
            reason?: string;
        };
        AthletePage: {
            items: components["schemas"]["AthleteSummary"][];
            /** Format: uuid */
            next_cursor: string | null;
        };
        AthleteSummary: {
            /** Format: uuid */
            athlete_id: string;
            /** Format: uuid */
            person_id: string;
            display_name: string;
            /** @enum {string} */
            participation: "regular" | "guest";
            archived: boolean;
            version: number;
        };
        CloseSessionRequest: {
            /** Format: uuid */
            operation_id: string;
            base_version: number;
        };
        CloseSessionResult: {
            /** Format: uuid */
            operation_id: string;
            session: components["schemas"]["TrainingSession"] & {
                /** @enum {string} */
                state?: "closed";
            };
            unmarked_count: number;
            /** @enum {string|null} */
            warning: null;
        } | {
            /** Format: uuid */
            operation_id: string;
            session: components["schemas"]["TrainingSession"] & {
                /** @enum {string} */
                state?: "closed";
            };
            unmarked_count: number;
            /** @enum {string} */
            warning: "UNMARKED_REMAIN";
        };
        /** @description Локальная ошибка принятого контракта S1: общая Error/auth-схема не меняется. current_version разрешённого target при конфликте версии, иначе null. Чужой объект даёт нейтральный 404 раньше проверки версии/ID. */
        S1CommandConflict: {
            /** @enum {string} */
            code: "ENTITY_VERSION_CONFLICT" | "SESSION_VERSION_CONFLICT" | "SESSION_CLOSED" | "SESSION_CANCELLED" | "ATHLETE_ARCHIVED" | "GUARDIAN_LINK_INACTIVE" | "OPERATION_ID_REUSED" | "ROSTER_EXCLUDED" | "ATHLETE_ALREADY_EXISTS" | "PERSON_ARCHIVED" | "RESULT_NOT_CURRENT" | "MEMBERSHIP_ENDED";
            message: string;
            request_id: string;
            /** Format: uuid */
            operation_id: string;
            current_version: number | null;
        };
        AddKnownRosterRequest: {
            /** Format: uuid */
            operation_id: string;
            base_version: number;
            /** Format: uuid */
            athlete_id: string;
            trial: boolean;
        };
        RosterCommandResult: {
            /** Format: uuid */
            operation_id: string;
            session: components["schemas"]["TrainingSession"];
            entry: components["schemas"]["RosterEntry"];
        };
        CreateSessionGuestRequest: {
            /** Format: uuid */
            operation_id: string;
            base_version: number;
            display_name: string;
            /** @description Необязательный номер; null — доступного номера нет. Номер не доказывает связь или права. */
            phone?: string | null;
            trial: boolean;
        };
        ExcludeRosterRequest: {
            /** Format: uuid */
            operation_id: string;
            base_version: number;
        };
    };
    responses: {
        /** @description Некорректный JSON, неизвестное/лишнее поле, UUID, дата или cursor. */
        Error400: {
            headers: {
                /**
                 * @description Приватные данные и токены не кешируются.
                 * @example no-store
                 */
                "Cache-Control"?: "no-store";
                /**
                 * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                 * @example synthetic-request-001
                 */
                "X-Request-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INVALID_REQUEST",
                 *       "message": "Синтетический пример безопасной ошибки.",
                 *       "request_id": "synthetic-request-001"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Нет действующей сессии; истечение или отзыв. Никаких профилей в ответе. */
        Error401: {
            headers: {
                /**
                 * @description Приватные данные и токены не кешируются.
                 * @example no-store
                 */
                "Cache-Control"?: "no-store";
                /**
                 * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                 * @example synthetic-request-001
                 */
                "X-Request-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHENTICATED",
                 *       "message": "Синтетический пример безопасной ошибки.",
                 *       "request_id": "synthetic-request-001"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Нет разрешения или проверка CSRF/Origin отклонена. */
        Error403: {
            headers: {
                /**
                 * @description Приватные данные и токены не кешируются.
                 * @example no-store
                 */
                "Cache-Control"?: "no-store";
                /**
                 * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                 * @example synthetic-request-001
                 */
                "X-Request-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ограничение частоты; Retry-After задаёт секунды ожидания. */
        Error429: {
            headers: {
                /**
                 * @description Приватные данные и токены не кешируются.
                 * @example no-store
                 */
                "Cache-Control"?: "no-store";
                /**
                 * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                 * @example synthetic-request-001
                 */
                "X-Request-ID"?: string;
                /**
                 * @description Число секунд до следующей попытки.
                 * @example 5
                 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "RATE_LIMITED",
                 *       "message": "Синтетический пример безопасной ошибки.",
                 *       "request_id": "synthetic-request-001"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Безопасная внутренняя ошибка; результат записи может быть неизвестен клиенту. */
        Error500: {
            headers: {
                /**
                 * @description Приватные данные и токены не кешируются.
                 * @example no-store
                 */
                "Cache-Control"?: "no-store";
                /**
                 * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                 * @example synthetic-request-001
                 */
                "X-Request-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INTERNAL_ERROR",
                 *       "message": "Синтетический пример безопасной ошибки.",
                 *       "request_id": "synthetic-request-001"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Временная недоступность; для команды результат может быть неизвестен. Повторить тот же ID/payload. */
        Error503: {
            headers: {
                /**
                 * @description Приватные данные и токены не кешируются.
                 * @example no-store
                 */
                "Cache-Control"?: "no-store";
                /**
                 * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                 * @example synthetic-request-001
                 */
                "X-Request-ID"?: string;
                /**
                 * @description Число секунд до следующей попытки.
                 * @example 5
                 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "SERVICE_UNAVAILABLE",
                 *       "message": "Синтетический пример безопасной ошибки.",
                 *       "request_id": "synthetic-request-001"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Объект отсутствует или вне разрешённого scope; существование чужого объекта не раскрывается. */
        Error404: {
            headers: {
                /**
                 * @description Приватные данные и токены не кешируются.
                 * @example no-store
                 */
                "Cache-Control"?: "no-store";
                /**
                 * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                 * @example synthetic-request-001
                 */
                "X-Request-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Синтетический пример безопасной ошибки.",
                 *       "request_id": "synthetic-request-001"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Тело запроса превышает 16 KiB. */
        Error413: {
            headers: {
                /**
                 * @description Приватные данные и токены не кешируются.
                 * @example no-store
                 */
                "Cache-Control"?: "no-store";
                /**
                 * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                 * @example synthetic-request-001
                 */
                "X-Request-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "PAYLOAD_TOO_LARGE",
                 *       "message": "Синтетический пример безопасной ошибки.",
                 *       "request_id": "synthetic-request-001"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Требуется application/json; form и text/plain не принимаются. */
        Error415: {
            headers: {
                /**
                 * @description Приватные данные и токены не кешируются.
                 * @example no-store
                 */
                "Cache-Control"?: "no-store";
                /**
                 * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                 * @example synthetic-request-001
                 */
                "X-Request-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNSUPPORTED_MEDIA_TYPE",
                 *       "message": "Синтетический пример безопасной ошибки.",
                 *       "request_id": "synthetic-request-001"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Кандидат клуба, проверяется через активный ClubMembership; не разрешение.
         * @example 00000000-0000-4000-8000-000000000101
         */
        TenantId: string;
        /**
         * @description Устойчивый ID занятия внутри проверенного tenant.
         * @example 00000000-0000-4000-8000-000000000501
         */
        SessionId: string;
        /**
         * @description Athlete ID в сохранённом составе этого занятия; не Account/Person ID.
         * @example 00000000-0000-4000-8000-000000000401
         */
        AthleteId: string;
        /**
         * @description Токен GET /access/csrf, связанный с preauth или действующей сессией; не сохранять на диске.
         * @example synthetic-csrf-token-0000000000000001
         */
        CsrfHeader: string;
        /**
         * @description Точное совпадение с настроенным HTTPS origin; отсутствие/null отклоняется.
         * @example https://judeos.example
         */
        Origin: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAssignedSessions: {
        parameters: {
            query: {
                /**
                 * @description Обязательная календарная дата в зоне клуба.
                 * @example 2026-10-07
                 */
                date: string;
                /**
                 * @description Размер страницы, default 50; значения вне диапазона — 400.
                 * @example 50
                 */
                limit?: number;
                /** @description Непрозрачный cursor из предыдущей страницы; отсутствует для первой. */
                cursor?: string;
            };
            header?: never;
            path: {
                /**
                 * @description Кандидат клуба, проверяется через активный ClubMembership; не разрешение.
                 * @example 00000000-0000-4000-8000-000000000101
                 */
                tenant_id: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Разрешённые занятия; пустой список допустим. */
            200: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            /** @description Метод не поддерживается; Allow содержит разрешённые методы этого пути. */
            405: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description Разрешённые методы этого конкретного пути.
                     * @example GET, POST
                     */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "METHOD_NOT_ALLOWED",
                     *       "message": "Синтетический пример безопасной ошибки.",
                     *       "request_id": "synthetic-request-001"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
            503: components["responses"]["Error503"];
        };
    };
    getSessionJournal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Кандидат клуба, проверяется через активный ClubMembership; не разрешение.
                 * @example 00000000-0000-4000-8000-000000000101
                 */
                tenant_id: components["parameters"]["TenantId"];
                /**
                 * @description Устойчивый ID занятия внутри проверенного tenant.
                 * @example 00000000-0000-4000-8000-000000000501
                 */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Версия занятия и независимые версии отметок. */
            200: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "session": {
                     *         "session_id": "00000000-0000-4000-8000-000000000501",
                     *         "tenant_id": "00000000-0000-4000-8000-000000000101",
                     *         "group": {
                     *           "id": "00000000-0000-4000-8000-000000000601",
                     *           "name": "Тестовая группа"
                     *         },
                     *         "venue": {
                     *           "id": "00000000-0000-4000-8000-000000000602",
                     *           "name": "Синтетический зал"
                     *         },
                     *         "starts_at": "2026-10-07T15:00:00Z",
                     *         "ends_at": "2026-10-07T16:00:00Z",
                     *         "state": "in_progress",
                     *         "version": 1
                     *       },
                     *       "roster": [
                     *         {
                     *           "athlete_id": "00000000-0000-4000-8000-000000000401",
                     *           "person_id": "00000000-0000-4000-8000-000000000301",
                     *           "display_name": "Тестовый спортсмен А",
                     *           "participation": "regular",
                     *           "trial": false,
                     *           "attendance": {
                     *             "athlete_id": "00000000-0000-4000-8000-000000000401",
                     *             "status": "unmarked",
                     *             "version": 0,
                     *             "recorded_at": null,
                     *             "recorded_by_account_id": null
                     *           }
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SessionJournal"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            /** @description Метод не поддерживается; Allow содержит разрешённые методы этого пути. */
            405: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description Разрешённые методы этого конкретного пути.
                     * @example GET
                     */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "METHOD_NOT_ALLOWED",
                     *       "message": "Синтетический пример безопасной ошибки.",
                     *       "request_id": "synthetic-request-001"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
            503: components["responses"]["Error503"];
        };
    };
    setAttendance: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Токен GET /access/csrf, связанный с preauth или действующей сессией; не сохранять на диске.
                 * @example synthetic-csrf-token-0000000000000001
                 */
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                /**
                 * @description Точное совпадение с настроенным HTTPS origin; отсутствие/null отклоняется.
                 * @example https://judeos.example
                 */
                Origin: components["parameters"]["Origin"];
            };
            path: {
                /**
                 * @description Кандидат клуба, проверяется через активный ClubMembership; не разрешение.
                 * @example 00000000-0000-4000-8000-000000000101
                 */
                tenant_id: components["parameters"]["TenantId"];
                /**
                 * @description Устойчивый ID занятия внутри проверенного tenant.
                 * @example 00000000-0000-4000-8000-000000000501
                 */
                session_id: components["parameters"]["SessionId"];
                /**
                 * @description Athlete ID в сохранённом составе этого занятия; не Account/Person ID.
                 * @example 00000000-0000-4000-8000-000000000401
                 */
                athlete_id: components["parameters"]["AthleteId"];
            };
            cookie?: never;
        };
        /** @description JSON, до 16 KiB; лишние поля и null вне nullable отклоняются. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "operation_id": "00000000-0000-4000-8000-000000000701",
                 *       "base_version": 0,
                 *       "status": "present"
                 *     }
                 */
                "application/json": components["schemas"]["SetAttendanceRequest"];
            };
        };
        responses: {
            /** @description Применено или повтор исходного успешного результата. */
            200: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description true для сохранённого результата; false для первой принятой команды.
                     * @example false
                     */
                    "Operation-Replayed"?: boolean;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "operation_id": "00000000-0000-4000-8000-000000000701",
                     *       "attendance": {
                     *         "athlete_id": "00000000-0000-4000-8000-000000000401",
                     *         "status": "present",
                     *         "version": 1,
                     *         "recorded_at": "2026-10-07T15:03:00Z",
                     *         "recorded_by_account_id": "00000000-0000-4000-8000-000000000001"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["AttendanceSaved"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            /** @description Метод не поддерживается; Allow содержит разрешённые методы этого пути. */
            405: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description Разрешённые методы этого конкретного пути.
                     * @example PUT
                     */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "METHOD_NOT_ALLOWED",
                     *       "message": "Синтетический пример безопасной ошибки.",
                     *       "request_id": "synthetic-request-001"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Конфликт версии, повтор ID с другим payload или запрет записи по состоянию. Только версия возвращает current, после проверки прав. */
            409: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description Присутствует для сохранённого результата конфликта версии; true на его повторе.
                     * @example false
                     */
                    "Operation-Replayed"?: boolean;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceCommandConflict"];
                };
            };
            413: components["responses"]["Error413"];
            415: components["responses"]["Error415"];
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
            503: components["responses"]["Error503"];
        };
    };
    listAthletes: {
        parameters: {
            query?: {
                /** @description Буквальная подстрока имени. */
                q?: string;
                limit?: number;
                cursor?: string;
                state?: "active" | "archived" | "all";
            };
            header?: never;
            path: {
                /** @description Непрозрачный ID; область проверяется сервером. */
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущий разрешённый результат. */
            200: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "athlete_id": "00000000-0000-4000-8000-000000000401",
                     *           "person_id": "00000000-0000-4000-8000-000000000301",
                     *           "display_name": "Синтетический участник",
                     *           "participation": "regular",
                     *           "archived": false,
                     *           "version": 1
                     *         }
                     *       ],
                     *       "next_cursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["AthletePage"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            /** @description Метод не поддерживается; Allow содержит разрешённые методы этого пути. */
            405: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description Разрешённые методы этого конкретного пути.
                     * @example GET, POST
                     */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "METHOD_NOT_ALLOWED",
                     *       "message": "Синтетический пример безопасной ошибки.",
                     *       "request_id": "synthetic-request-001"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
            503: components["responses"]["Error503"];
        };
    };
    closeSession: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Токен GET /access/csrf, связанный с preauth или действующей сессией; не сохранять на диске.
                 * @example synthetic-csrf-token-0000000000000001
                 */
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                /**
                 * @description Точное совпадение с настроенным HTTPS origin; отсутствие/null отклоняется.
                 * @example https://judeos.example
                 */
                Origin: components["parameters"]["Origin"];
            };
            path: {
                /**
                 * @description Кандидат клуба, проверяется через активный ClubMembership; не разрешение.
                 * @example 00000000-0000-4000-8000-000000000101
                 */
                tenant_id: components["parameters"]["TenantId"];
                /**
                 * @description Устойчивый ID занятия внутри проверенного tenant.
                 * @example 00000000-0000-4000-8000-000000000501
                 */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "operation_id": "00000000-0000-4000-8000-000000000901",
                 *       "base_version": 1
                 *     }
                 */
                "application/json": components["schemas"]["CloseSessionRequest"];
            };
        };
        responses: {
            /** @description Синтетический пример planned-результата принятого контракта. */
            200: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description true при возврате исходного результата после проверки текущих прав/состояния.
                     * @example false
                     */
                    "Operation-Replayed"?: boolean;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "operation_id": "00000000-0000-4000-8000-000000000901",
                     *       "session": {
                     *         "session_id": "00000000-0000-4000-8000-000000000501",
                     *         "tenant_id": "00000000-0000-4000-8000-000000000101",
                     *         "group": {
                     *           "id": "00000000-0000-4000-8000-000000000601",
                     *           "name": "Тестовая группа"
                     *         },
                     *         "venue": {
                     *           "id": "00000000-0000-4000-8000-000000000602",
                     *           "name": "Синтетический зал"
                     *         },
                     *         "starts_at": "2026-10-07T15:00:00Z",
                     *         "ends_at": "2026-10-07T16:00:00Z",
                     *         "state": "closed",
                     *         "version": 2
                     *       },
                     *       "unmarked_count": 1,
                     *       "warning": "UNMARKED_REMAIN"
                     *     }
                     */
                    "application/json": components["schemas"]["CloseSessionResult"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            /** @description Метод не поддерживается; Allow содержит разрешённые методы этого пути. */
            405: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description Разрешённые методы этого конкретного пути.
                     * @example POST
                     */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "METHOD_NOT_ALLOWED",
                     *       "message": "Синтетический пример безопасной ошибки.",
                     *       "request_id": "synthetic-request-001"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Версия, состояние или неактуальная связь; без частичного эффекта. Точный повтор конфликта версии терминален для ID. */
            409: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ENTITY_VERSION_CONFLICT",
                     *       "message": "Синтетический конфликт версии.",
                     *       "request_id": "synthetic-s1-request",
                     *       "operation_id": "00000000-0000-4000-8000-000000000901",
                     *       "current_version": 2
                     *     }
                     */
                    "application/json": components["schemas"]["S1CommandConflict"];
                };
            };
            413: components["responses"]["Error413"];
            415: components["responses"]["Error415"];
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
            503: components["responses"]["Error503"];
        };
    };
    addKnownRosterAthlete: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Токен GET /access/csrf, связанный с preauth или действующей сессией; не сохранять на диске.
                 * @example synthetic-csrf-token-0000000000000001
                 */
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                /**
                 * @description Точное совпадение с настроенным HTTPS origin; отсутствие/null отклоняется.
                 * @example https://judeos.example
                 */
                Origin: components["parameters"]["Origin"];
            };
            path: {
                /**
                 * @description Кандидат клуба, проверяется через активный ClubMembership; не разрешение.
                 * @example 00000000-0000-4000-8000-000000000101
                 */
                tenant_id: components["parameters"]["TenantId"];
                /**
                 * @description Устойчивый ID занятия внутри проверенного tenant.
                 * @example 00000000-0000-4000-8000-000000000501
                 */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "operation_id": "00000000-0000-4000-8000-000000000901",
                 *       "base_version": 1,
                 *       "athlete_id": "00000000-0000-4000-8000-000000000401",
                 *       "trial": false
                 *     }
                 */
                "application/json": components["schemas"]["AddKnownRosterRequest"];
            };
        };
        responses: {
            /** @description Синтетический пример planned-результата принятого контракта. */
            200: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description true при возврате исходного результата после проверки текущих прав/состояния.
                     * @example false
                     */
                    "Operation-Replayed"?: boolean;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "operation_id": "00000000-0000-4000-8000-000000000901",
                     *       "session": {
                     *         "session_id": "00000000-0000-4000-8000-000000000501",
                     *         "tenant_id": "00000000-0000-4000-8000-000000000101",
                     *         "group": {
                     *           "id": "00000000-0000-4000-8000-000000000601",
                     *           "name": "Тестовая группа"
                     *         },
                     *         "venue": {
                     *           "id": "00000000-0000-4000-8000-000000000602",
                     *           "name": "Синтетический зал"
                     *         },
                     *         "starts_at": "2026-10-07T15:00:00Z",
                     *         "ends_at": "2026-10-07T16:00:00Z",
                     *         "state": "in_progress",
                     *         "version": 2
                     *       },
                     *       "entry": {
                     *         "athlete_id": "00000000-0000-4000-8000-000000000401",
                     *         "person_id": "00000000-0000-4000-8000-000000000301",
                     *         "display_name": "Тестовый спортсмен А",
                     *         "participation": "visit",
                     *         "trial": false,
                     *         "attendance": {
                     *           "athlete_id": "00000000-0000-4000-8000-000000000401",
                     *           "status": "unmarked",
                     *           "version": 0,
                     *           "recorded_at": null,
                     *           "recorded_by_account_id": null
                     *         },
                     *         "primary_contact": {
                     *           "display_name": "Синтетический представитель",
                     *           "phone": null
                     *         },
                     *         "admission": null,
                     *         "excluded": false
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["RosterCommandResult"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            /** @description Метод не поддерживается; Allow содержит разрешённые методы этого пути. */
            405: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description Разрешённые методы этого конкретного пути.
                     * @example POST
                     */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "METHOD_NOT_ALLOWED",
                     *       "message": "Синтетический пример безопасной ошибки.",
                     *       "request_id": "synthetic-request-001"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Версия, состояние или неактуальная связь; без частичного эффекта. Точный повтор конфликта версии терминален для ID. */
            409: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ENTITY_VERSION_CONFLICT",
                     *       "message": "Синтетический конфликт версии.",
                     *       "request_id": "synthetic-s1-request",
                     *       "operation_id": "00000000-0000-4000-8000-000000000901",
                     *       "current_version": 2
                     *     }
                     */
                    "application/json": components["schemas"]["S1CommandConflict"];
                };
            };
            413: components["responses"]["Error413"];
            415: components["responses"]["Error415"];
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
            503: components["responses"]["Error503"];
        };
    };
    createSessionGuest: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Токен GET /access/csrf, связанный с preauth или действующей сессией; не сохранять на диске.
                 * @example synthetic-csrf-token-0000000000000001
                 */
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                /**
                 * @description Точное совпадение с настроенным HTTPS origin; отсутствие/null отклоняется.
                 * @example https://judeos.example
                 */
                Origin: components["parameters"]["Origin"];
            };
            path: {
                /**
                 * @description Кандидат клуба, проверяется через активный ClubMembership; не разрешение.
                 * @example 00000000-0000-4000-8000-000000000101
                 */
                tenant_id: components["parameters"]["TenantId"];
                /**
                 * @description Устойчивый ID занятия внутри проверенного tenant.
                 * @example 00000000-0000-4000-8000-000000000501
                 */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "operation_id": "00000000-0000-4000-8000-000000000901",
                 *       "base_version": 1,
                 *       "display_name": "Синтетический гость",
                 *       "trial": true
                 *     }
                 */
                "application/json": components["schemas"]["CreateSessionGuestRequest"];
            };
        };
        responses: {
            /** @description Синтетический пример planned-результата принятого контракта. */
            201: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description true при возврате исходного результата после проверки текущих прав/состояния.
                     * @example false
                     */
                    "Operation-Replayed"?: boolean;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "operation_id": "00000000-0000-4000-8000-000000000901",
                     *       "session": {
                     *         "session_id": "00000000-0000-4000-8000-000000000501",
                     *         "tenant_id": "00000000-0000-4000-8000-000000000101",
                     *         "group": {
                     *           "id": "00000000-0000-4000-8000-000000000601",
                     *           "name": "Тестовая группа"
                     *         },
                     *         "venue": {
                     *           "id": "00000000-0000-4000-8000-000000000602",
                     *           "name": "Синтетический зал"
                     *         },
                     *         "starts_at": "2026-10-07T15:00:00Z",
                     *         "ends_at": "2026-10-07T16:00:00Z",
                     *         "state": "in_progress",
                     *         "version": 2
                     *       },
                     *       "entry": {
                     *         "athlete_id": "00000000-0000-4000-8000-000000000401",
                     *         "person_id": "00000000-0000-4000-8000-000000000301",
                     *         "display_name": "Тестовый спортсмен А",
                     *         "participation": "guest",
                     *         "trial": true,
                     *         "attendance": {
                     *           "athlete_id": "00000000-0000-4000-8000-000000000401",
                     *           "status": "unmarked",
                     *           "version": 0,
                     *           "recorded_at": null,
                     *           "recorded_by_account_id": null
                     *         },
                     *         "primary_contact": {
                     *           "display_name": "Синтетический представитель",
                     *           "phone": null
                     *         },
                     *         "admission": null,
                     *         "excluded": false
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["RosterCommandResult"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            /** @description Метод не поддерживается; Allow содержит разрешённые методы этого пути. */
            405: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description Разрешённые методы этого конкретного пути.
                     * @example POST
                     */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "METHOD_NOT_ALLOWED",
                     *       "message": "Синтетический пример безопасной ошибки.",
                     *       "request_id": "synthetic-request-001"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Версия, состояние или неактуальная связь; без частичного эффекта. Точный повтор конфликта версии терминален для ID. */
            409: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ENTITY_VERSION_CONFLICT",
                     *       "message": "Синтетический конфликт версии.",
                     *       "request_id": "synthetic-s1-request",
                     *       "operation_id": "00000000-0000-4000-8000-000000000901",
                     *       "current_version": 2
                     *     }
                     */
                    "application/json": components["schemas"]["S1CommandConflict"];
                };
            };
            413: components["responses"]["Error413"];
            415: components["responses"]["Error415"];
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
            503: components["responses"]["Error503"];
        };
    };
    excludeRosterAthlete: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Токен GET /access/csrf, связанный с preauth или действующей сессией; не сохранять на диске.
                 * @example synthetic-csrf-token-0000000000000001
                 */
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
                /**
                 * @description Точное совпадение с настроенным HTTPS origin; отсутствие/null отклоняется.
                 * @example https://judeos.example
                 */
                Origin: components["parameters"]["Origin"];
            };
            path: {
                /**
                 * @description Кандидат клуба, проверяется через активный ClubMembership; не разрешение.
                 * @example 00000000-0000-4000-8000-000000000101
                 */
                tenant_id: components["parameters"]["TenantId"];
                /**
                 * @description Устойчивый ID занятия внутри проверенного tenant.
                 * @example 00000000-0000-4000-8000-000000000501
                 */
                session_id: components["parameters"]["SessionId"];
                /** @description Непрозрачный ID в проверенном клубе; права проверяются на target. */
                athlete_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "operation_id": "00000000-0000-4000-8000-000000000901",
                 *       "base_version": 1
                 *     }
                 */
                "application/json": components["schemas"]["ExcludeRosterRequest"];
            };
        };
        responses: {
            /** @description Синтетический пример planned-результата принятого контракта. */
            200: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description true при возврате исходного результата после проверки текущих прав/состояния.
                     * @example false
                     */
                    "Operation-Replayed"?: boolean;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "operation_id": "00000000-0000-4000-8000-000000000901",
                     *       "session": {
                     *         "session_id": "00000000-0000-4000-8000-000000000501",
                     *         "tenant_id": "00000000-0000-4000-8000-000000000101",
                     *         "group": {
                     *           "id": "00000000-0000-4000-8000-000000000601",
                     *           "name": "Тестовая группа"
                     *         },
                     *         "venue": {
                     *           "id": "00000000-0000-4000-8000-000000000602",
                     *           "name": "Синтетический зал"
                     *         },
                     *         "starts_at": "2026-10-07T15:00:00Z",
                     *         "ends_at": "2026-10-07T16:00:00Z",
                     *         "state": "in_progress",
                     *         "version": 2
                     *       },
                     *       "entry": {
                     *         "athlete_id": "00000000-0000-4000-8000-000000000401",
                     *         "person_id": "00000000-0000-4000-8000-000000000301",
                     *         "display_name": "Тестовый спортсмен А",
                     *         "participation": "regular",
                     *         "trial": false,
                     *         "attendance": {
                     *           "athlete_id": "00000000-0000-4000-8000-000000000401",
                     *           "status": "unmarked",
                     *           "version": 0,
                     *           "recorded_at": null,
                     *           "recorded_by_account_id": null
                     *         },
                     *         "primary_contact": null,
                     *         "admission": null,
                     *         "excluded": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["RosterCommandResult"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            /** @description Метод не поддерживается; Allow содержит разрешённые методы этого пути. */
            405: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    /**
                     * @description Разрешённые методы этого конкретного пути.
                     * @example POST
                     */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "METHOD_NOT_ALLOWED",
                     *       "message": "Синтетический пример безопасной ошибки.",
                     *       "request_id": "synthetic-request-001"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Версия, состояние или неактуальная связь; без частичного эффекта. Точный повтор конфликта версии терминален для ID. */
            409: {
                headers: {
                    /**
                     * @description Приватные данные и токены не кешируются.
                     * @example no-store
                     */
                    "Cache-Control"?: "no-store";
                    /**
                     * @description Безопасная корреляция диагностики; не секрет и не ID человека.
                     * @example synthetic-request-001
                     */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ENTITY_VERSION_CONFLICT",
                     *       "message": "Синтетический конфликт версии.",
                     *       "request_id": "synthetic-s1-request",
                     *       "operation_id": "00000000-0000-4000-8000-000000000901",
                     *       "current_version": 2
                     *     }
                     */
                    "application/json": components["schemas"]["S1CommandConflict"];
                };
            };
            413: components["responses"]["Error413"];
            415: components["responses"]["Error415"];
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
            503: components["responses"]["Error503"];
        };
    };
}
